name: BuildTools
main: au.com.mineauz.buildtools.Main
version: 1.0.0
author: _Razz_

commands:
  buildtools:
    description: The BuildTools base command.
    usage: Invalid command. Type "/buildtools help" for help
    permission: buildtools.command
    permisison-message: You don't have permission to use this command <permission>
    aliases: [bt]

permissions:
  buildtools.command:
    description: Allows a player to use the base command.
    default: op
  buildtools.command.*:
    children:
      buildtools.command.debug: true
      buildtools.command.pattern: true
      buildtools.command.undo: true
      buildtools.command.redo: true
      buildtools.command.selection: true
  buildtools.command.basic:
    description: Basic command permissions for players.
    children:
      buildtools.command.pattern: true
      buildtools.command.undo: true
      buildtools.command.redo: true
      buildtools.command.selection: true
  buildtools.command.debug:
    default: op
  buildtools.command.pattern:
    default: op
  buildtools.command.undo:
    default: op
  buildtools.command.redo:
    default: op
  buildtools.command.selection:
    default: op
  buildtools.bypasslimits:
    description: Allows a player to bypass all limits.
    children:
      buildtools.bypassheightlimit: true
      buildtools.bypassvolumelimit: true
      buildtools.bypassdisabledblocks: true
  buildtools.bypassheightlimit:
    default: op
  buildtools.bypassvolumelimit:
    default: false
  buildtools.bypassdisabledblocks:
    default: false