# Maximum volume allowed for players to use BuildTools.
# More groups can be added to allow certain players to build larger.
# Permission for added groups: buildtools.maxvolume.<groupName>
maxVolume:
  default: 103680

# Height limits for players to use BuildTools, Min 0, Max 255.
# More groups can be added to allow certain players to build higher/lower.
# First item on list is minimum height, second is maximum.
# Permission for added groups: buildtools.hightlimit.<groupName>
heightLimits:
  default:
  - -63
  - 320

# Block materials that cannot be used in BuildTools.
# More groups can be added to disallow specific blocks per group.
# Permission for added groups: buildtools.disabledblocks.<groupName>
disabledBlocks:
  default:
  - ACACIA_BUTTON
  - ACACIA_DOOR
  - ACTIVATOR_RAIL
  - AMETHYST_CLUSTER
  - AMETHYST_SHARD
  - ANVIL
  - ARMOR_STAND
  - AXOLOTL_BUCKET
  - BAMBOO
  - BANNER
  - BARRIER
  - BEACON
  - BED
  - BED_BLOCK
  - BIRCH_BUTTON
  - BIRCH_DOOR
  - BLACK_CANDLE
  - BLUE_CANDLE
  - BOAT
  - BREWING_STAND
  - BROWN_CANDLE
  - BROWN_MUSHROOM
  - BURNING_FURNACE
  - CACTUS
  - CAKE_BLOCK
  - CAMPFIRE
  - CANDLE
  - CARPET
  - CARROT
  - CAULDRON
  - CHAIN
  - CHEST
  - CHEST_MINECART
  - COMMAND
  - COMMAND_BLOCK_MINECART
  - CRIMSON_ROOTS
  - CROPS
  - CYAN_CANDLE
  - DARK_OAK_BUTTON
  - DARK_OAK_DOOR
  - DAYLIGHT_DETECTOR
  - DEAD_BUSH
  - DETECTOR_RAIL
  - DIODE
  - DISPENSER
  - DOUBLE_PLANT
  - DRAGON_EGG
  - DROPPER
  - EMPTY_MAP
  - ENCHANTMENT_TABLE
  - END_CRYSTAL
  - ENDER_PORTAL
  - ENDER_PORTAL_FRAME
  - END_ROD
  - EXPLOSIVE_MINECART
  - FIRE
  - FLOWER_POT
  - FURNACE_MINECART
  - GLOW_BERRIES
  - GLOW_LICHEN
  - GRAY_CANDLE
  - GREEN_CANDLE
  - HOPPER
  - HOPPER_MINECART
  - HUGE_MUSHROOM_1
  - HUGE_MUSHROOM_2
  - IRON_DOOR
  - IRON_DOOR_BLOCK
  - ITEM_FRAME
  - JUKEBOX
  - JUNGLE_BUTTON
  - JUNGLE_DOOR
  - LADDER
  - LARGE_AMETHYST_BUD
  - LAVA
  - LEVER
  - LIGHT_BLUE_CANDLE
  - LIGHT_GRAY_CANDLE
  - LIGHTNING_ROD
  - LIME_CANDLE
  - MAGENTA_CANDLE
  - MANGROVE_PROPAGULe
  - MEDIUM_AMETHYST_BUD
  - MINECART
  - MOB_SPAWNER
  - NETHER_SPROUTS
  - OCHRE_FROGLIGHT
  - ORANGE_CANDLE
  - PAINTING
  - PEARLESCENT_FROGLIGHT
  - PINK_CANDLE
  - PISTON_BASE
  - PISTON_EXTENSION
  - PISTON_MOVING_PIECE
  - PISTON_STICKY_BASE
  - PORTAL
  - POTATO
  - POWERED_MINECART
  - POWERED_RAIL
  - PURPLE_CANDLE
  - RAILS
  - REDSTONE
  - REDSTONE_BLOCK
  - REDSTONE_COMPARATOR
  - REDSTONE_COMPARATOR_OFF
  - REDSTONE_COMPARATOR_ON
  - REDSTONE_LAMP_OFF
  - REDSTONE_LAMP_ON
  - REDSTONE_TORCH_OFF
  - REDSTONE_TORCH_ON
  - REDSTONE_WIRE
  - RED_CANDLE
  - RED_MUSHROOM
  - RED_ROSE
  - SAPLING
  - SCULK_SENSOR
  - SCULK_SHRIEKER
  - SEA_PICKLE
  - SIGN
  - SIGN_POST
  - SKULL
  - SMALL_AMETHYST_BUD
  - SOUL_CAMPFIRE
  - SOUL_TORCH
  - SPONGE
  - SPRUCE_BUTTON
  - SPRUCE_DOOR
  - STANDING_BANNER
  - STONE_BUTTON
  - STORAGE_MINECART
  - TALL_GRASS
  - TNT
  - TNT_MINECART
  - TORCH
  - TRAPPED_CHEST
  - TRAP_DOOR
  - TRIPWIRE_HOOK
  - TWISTING_VINES
  - VERDANT_FROGLIGHT
  - VINE
  - WALL_BANNER
  - WALL_SIGN
  - WALL_TORCH
  - WARPED_ROOTS
  - WATCH
  - WATER
  - WATER_LILY
  - WEB
  - WEEPING_VINES
  - WHITE_CANDLE
  - WOODEN_BUTTON
  - WOODEN_DOOR
  - YELLOW_CANDLE

# Maximum amount of time the generator can lag the server in milliseconds.
# This is to prevent large generations from lagging the server. A larger
# number may lag the server more but also generate more blocks per tick,
# smaller numbers will generate less blocks per tick but also lag less.
# (Bigger number = faster block generation but more lag, 
# smaller number = slower block gereation but less lag) 
# 10 milliseconds default.
generatorMaxDelay: 10